apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: prometheus
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 3000
      nodePort: 30007
